spring.application.name=security-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:secret}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:local-development-secret-key-change-me-1234567890}